In [4]:
from sklearn import svm, datasets
import pandas as pd

In [5]:
iris = datasets.load_iris()

In [6]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),flower
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.2)

In [13]:
model = svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9666666666666667

In [14]:
from sklearn.model_selection import cross_val_score

In [15]:
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [16]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [17]:
cross_val_score(svm.SVC(kernel='linear',C=20,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

# Using GridSearch CV

In [18]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(), {
    'C': [1,10,20],
    'kernel' : ['rbf','linear']
}, cv=5, return_train_score = False)

clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00118017, 0.00076613, 0.00080757, 0.00076604, 0.00080366,
        0.0007555 ]),
 'std_fit_time': array([2.21682615e-04, 3.34730175e-05, 3.51831511e-05, 4.23620908e-05,
        1.66984261e-05, 2.46384118e-05]),
 'mean_score_time': array([0.0005228 , 0.00039663, 0.00041904, 0.00038524, 0.00041265,
        0.00037932]),
 'std_score_time': array([3.34668356e-05, 9.67944196e-06, 1.78145750e-05, 1.05135835e-05,
        1.97547598e-05, 1.13413089e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        ]),
 'split1_test_score': array([0.96666667, 1.        , 1.        , 1.        , 1.        ,
        1.        ]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.96666667,
        0.9       ]),
 'split3_test_score': array([0.93333333, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.96666667, 0.98      , 0.98      , 0.97333333, 0.98      ,
        0.96666667]),
 'std_test_score': array([0.02108185, 0.01632993, 0.01632993, 0.03887301, 0.01632993,
        0.0421637 ]),
 'rank_test_score': array([5, 1, 1, 4, 1, 5], dtype=int32)}

In [19]:
df = pd.DataFrame(clf.cv_results_)

In [20]:
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001180,0.000222,0.000523,0.000033,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,0.966667,0.966667,0.933333,1.0,0.966667,0.021082,5
1,0.000766,0.000033,0.000397,0.000010,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.000808,0.000035,0.000419,0.000018,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.000766,0.000042,0.000385,0.000011,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.000804,0.000017,0.000413,0.000020,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
5,0.000756,0.000025,0.000379,0.000011,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,5

In [21]:
df[['param_C','param_kernel','mean_test_score']]

  param_C param_kernel  mean_test_score
0       1          rbf         0.966667
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.980000
5      20       linear         0.966667

# Using RandomizedSearchCV

In [22]:
from sklearn.model_selection import RandomizedSearchCV
clf = RandomizedSearchCV(svm.SVC(gamma='auto'), {
    'C': [1,10,20],
    'kernel' : ['rbf','linear']
}, cv=5, return_train_score = False, n_iter=2)

clf.fit(iris.data,iris.target)
df = pd.DataFrame(clf.cv_results_)[['param_C','param_kernel','mean_test_score']]

In [23]:
df

  param_C param_kernel  mean_test_score
0      20          rbf         0.966667
1       1       linear         0.980000

## Finding the best model

In [24]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [27]:
model_params = {
    'svm': {
        'model':svm.SVC(gamma='auto'),
        'params':{
            'C':range(1,20),
            'kernel':['rbf','linear']
        }
    },
    'random_forest': {
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators': range(1,20)
            
        }
    },
    'logistic_regression': {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params':{
            'C': range(1,20)
        }
    }
}

In [28]:
scores = []

for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'],mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })

In [30]:
df = pd.DataFrame(scores)

In [31]:
df

                 model  best_score                best_params
0                  svm    0.986667  {'C': 4, 'kernel': 'rbf'}
1        random_forest    0.966667        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 4}

# Example

New notebook called sklearn Digit dataset