In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/kaggle/input/titanic/train.csv')
df.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [3]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis = 'columns',inplace = True)

In [4]:
df

     Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [5]:
target = df.Survived
inputs = df.drop('Survived',axis = 'columns')

In [6]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head()

   female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [7]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head()

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [8]:
inputs.drop('Sex',axis='columns',inplace=True)
inputs.head()

   Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [9]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [10]:
inputs.isnull().sum()

Pclass      0
Age       177
Fare        0
female      0
male        0
dtype: int64

In [11]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.isnull().sum()

Pclass    0
Age       0
Fare      0
female    0
male      0
dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(inputs,target,test_size=0.2)

In [13]:
x_train.shape

(712, 5)

In [14]:
x_test.shape

(179, 5)

In [15]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [16]:
model.fit(x_train,y_train)

GaussianNB()

In [17]:
model.score(x_test,y_test)

0.7988826815642458

# Let me check the scores for all other models i have learnt

In [18]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

In [19]:
from sklearn.model_selection import cross_val_score
import numpy as np

In [20]:
np.average(cross_val_score(LinearRegression(),inputs,target))

0.3651090031642523

In [21]:
np.average(cross_val_score(LogisticRegression(),inputs,target))

0.7878727010231624

In [22]:
np.average(cross_val_score(SVC(),inputs,target))

0.6701462557278262

In [23]:
np.average(cross_val_score(DecisionTreeClassifier(),inputs,target))

0.7778482204506936

In [24]:
np.average(cross_val_score(RandomForestClassifier(n_estimators=40),inputs,target))

0.8014123407193523

In [25]:
np.average(cross_val_score(GaussianNB(),inputs,target))

0.7845019145063085

In [26]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(inputs,target)

RandomForestClassifier(n_estimators=40)

In [27]:
test = pd.read_csv('/kaggle/input/titanic/test.csv')
test.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis = 'columns',inplace = True)

In [28]:
dummies = pd.get_dummies(test.Sex)
dummies.head()

test = pd.concat([test,dummies],axis='columns')
test.drop('Sex',axis='columns',inplace=True)
test.head()

   Pclass   Age     Fare  female  male
0       3  34.5   7.8292       0     1
1       3  47.0   7.0000       1     0
2       2  62.0   9.6875       0     1
3       3  27.0   8.6625       0     1
4       3  22.0  12.2875       1     0

In [29]:
test.isnull().sum()

Pclass     0
Age       86
Fare       1
female     0
male       0
dtype: int64

In [30]:
test.Age = test.Age.fillna(test.Age.mean())
test.Fare = test.Fare.fillna(test.Fare.mean())
test.isnull().sum()

Pclass    0
Age       0
Fare      0
female    0
male      0
dtype: int64

In [31]:
y_pred = rf.predict(test)

In [32]:
test_df = pd.read_csv('/kaggle/input/titanic/test.csv')

In [33]:
ans = pd.DataFrame(test_df['PassengerId'])

In [34]:
ans['Survived'] = y_pred

In [35]:
ans.to_csv("Random Forest titanic.csv",index = False)

# Lets continue with Naive Bayers

In [47]:
df = pd.read_csv('/kaggle/input/sms-spam-collection-dataset/spam.csv',encoding='ISO-8859-1')

In [48]:
df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis='columns',inplace=True)

In [54]:
df.columns = ['category','messages']

In [56]:
df.groupby('category').describe()

         messages                                                            \
            count unique                                                top
category
ham          4825   4516                             Sorry, I'll call later
spam          747    653  Please call our customer service representativ...


         freq
category
ham        30
spam        4

In [57]:
df['spam'] = df['category'].apply(lambda x: 1 if x == 'spam' else 0)
df.head()

  category                                           messages  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

### Count vetorizer for converting text

In [59]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()

In [68]:
# inputs = v.fit_transform(df.messages.values)
# x_train_count.toarray().shape

(4179, 7578)

In [81]:
x_train,x_test,y_train,y_test = train_test_split(df.messages,df.spam,test_size=0.25)

In [69]:
# x_train,x_test,y_train,y_test = train_test_split(inputs,df.spam,test_size=0.25)

In [78]:
from sklearn.naive_bayes import MultinomialNB
# model = MultinomialNB()
# model.fit(x_train,y_train)

MultinomialNB()

In [79]:
# model.score(x_test,y_test)

0.9820531227566404

In [76]:
# from sklearn.naive_bayes import GaussianNB
# model = GaussianNB()
# model.fit(x_train.toarray(),y_train)
# model.score(x_test.toarray(),y_test)

0.9095477386934674

In [77]:
# from sklearn.naive_bayes import BernoulliNB
# model = BernoulliNB()
# model.fit(x_train,y_train)
# model.score(x_test,y_test)

0.9798994974874372

In [80]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [82]:
clf.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [83]:
clf.score(x_test,y_test)

0.9921033740129217

# Example

In [84]:
from sklearn.datasets import load_wine
wine = load_wine()

In [85]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [89]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [92]:
df = pd.DataFrame(wine.data,columns=wine.feature_names)

In [96]:
target = pd.DataFrame(wine.target,columns=['target'])

In [97]:
target

     target
0         0
1         0
2         0
3         0
4         0
..      ...
173       2
174       2
175       2
176       2
177       2

[178 rows x 1 columns]

In [98]:
gnb = GaussianNB()
mnb = MultinomialNB()

In [99]:
x_train,x_test,y_train,y_test = train_test_split(df,target,test_size=0.25)

In [100]:
gnb.fit(x_train,y_train)
gnb.score(x_test,y_test)

/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.9777777777777777

In [101]:
mnb.fit(x_train,y_train)
mnb.score(x_test,y_test)

/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.7777777777777778

In [103]:
from sklearn.model_selection import cross_val_score
import numpy as np

In [104]:
np.average(cross_val_score(GaussianNB(),df,target))

/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.9663492063492063

In [105]:
np.average(cross_val_score(MultinomialNB(),df,target))

/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.843968253968254